package com.miaoshaSystem.dao;

import com.miaoshaSystem.eneity.OrderDO;
import org.springframework.stereotype.Component;

@Component
public interface OrderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order_info
     *
     * @mbg.generated Tue Jun 23 11:20:13 BST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order_info
     *
     * @mbg.generated Tue Jun 23 11:20:13 BST 2020
     */
    int insert(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order_info
     *
     * @mbg.generated Tue Jun 23 11:20:13 BST 2020
     */
    int insertSelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order_info
     *
     * @mbg.generated Tue Jun 23 11:20:13 BST 2020
     */
    OrderDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order_info
     *
     * @mbg.generated Tue Jun 23 11:20:13 BST 2020
     */
    int updateByPrimaryKeySelective(OrderDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Order_info
     *
     * @mbg.generated Tue Jun 23 11:20:13 BST 2020
     */
    int updateByPrimaryKey(OrderDO record);
}